# Site
repository: SionAn.github.io #sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sion An
title: Ph.D. Candidate, Department of Robotics and Mechatronics Engineering, DGIST
email: sionan624@gmail.com
#website: SionAn.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  SionAn
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0002-3800-7158

# Additional icon links
additional_links:
  - title: Google Scholar
    icon: fab fa-google
    url: https://scholar.google.com/citations?user=fr1Fb5UAAAAJ&hl=ko

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/SionAn.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Sion An and I'm a Ph.D. Candidate in [MISPL](https://sites.google.com/view/mispl/home) at Daegu Gyeongbuk Institute of Science and Technology (DGIST) advised by [Professor Sang Hyun Park](https://sites.google.com/view/mispl/members/professor).
  I obtaind my B.S. from DGIST in February 2020. 
  
  My research statement is as follows:
  Few-shot learning is a subset of deep learning algorithms and necessitates only a small set of labeled data. This facilitates the application of AI across diverse fields with limited labeled datasets. A topic of interest is few-shot learning for the development of tailored AI solutions e.g., personalized/targeted tasks.

  Keywords: <mark>Few-shot Learning</mark>, <mark>Medical Image and Signal Processing</mark>, <mark>Brain-Computer Interfaces</mark>

content:
  - title: Education
    layout: list
    content:
      - layout: left
        sub_title: 2020.03 - Present
        description: <b>Combined Undergraduate-Graduate Program</b>, Department of Robotics and Mechatronics Engineering, Daegu Gyeongbuk Institute of Science and Technology (DGIST), Daegu, South Korea.
      - layout: left
        sub_title: 2015.03 - 2020.02
        description: <b>Bachelor of Engineering</b>, School of Undergraduate Studies, Daegu Gyeongbuk Institute of Science and Technology (DGIST), Daegu, South Korea.

  - title: Research Experiences # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        sub_title: 2024.01 - Present
        description: <b>Visiting Student</b> at <a href="https://www.med.upenn.edu/shenlab/" target="_blank">Shen Lab</a> advised by Professor Li Shen
      - layout: left
        sub_title: 2017.03 - 2017.12
        description: <b>Undergraduate Group Research Program (UGRP)</b> at <a href="https://dgist-lab.wixsite.com/brainlab" target="_blank">BRAINLab</a> advised by Professor Jinung An
      - layout: left
        sub_title: 2017.01 - 2018.02
        description: <b>Undergraduate Research Assistant</b> at <a href="https://mems.dgist.ac.kr/" target="_blank">DEMRC</a> advised by Professor Hongsoo Choi

  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        sub_title: Articles in Submission/Preparation
      - layout: left
        sub_title: Under Review
        description: Ullah, I., <b>An, S.</b>, Chikontwe, P., Kang, M., Choi, J., & Park, S. H. 
          "Video Domain Adaptation for Semantic Segmentation using Perceptual Consistency Matching."
          Neural Networks (NN).
      - layout: left
        sub_title: Under Review
        description: <b>An, S.</b>, Kim, S., Chikontwe, P., Jung, J., Jeon, H., Kim, J., & Park, S. H. 
          "Few shot Anomaly Detection using Positive Unlabeled Learning with Cycle Consistency and Co-occurrence Features."
          Expert Systems With Applications (ESWA).

      - layout: top-middle
        sub_title: Journal Articles
      - layout: left
        sub_title: 2023
        index: J3
        paper_link:
          url: https://ieeexplore.ieee.org/document/10167679
          icon: fas fa-paperclip
          title: Paper Link
        code_link:
          url: https://github.com/SionAn/FewShotEEG
          icon: fab fa-github
          title: Code Link
        description: <b>An, S.</b>, Kim, S., Chikontwe, P., & Park, S. H. 
                    "Dual Attention Relation Network with Fine-Tuning for Few Shot EEG Motor Imagery Classification." 
                    IEEE Transactions on Neural Networks and Learning Systems (TNNLS).

      - layout: left
        sub_title: 2023
        index: J2
        paper_link:
          url: https://www.sciencedirect.com/science/article/pii/S0031320322007713
          icon: fas fa-paperclip
          title: Paper Link
        description: Kim, S., Chikontwe, P., <b>An, S.</b>, & Park, S. H. 
                    "Uncertainty-aware semi-supervised few shot segmentation." 
                    Pattern Recognition (PR).
      - layout: left
        sub_title: 2022
        index: J1
        paper_link:
          url: https://ieeexplore.ieee.org/document/9783070
          icon: fas fa-paperclip
          title: Paper Link
        description: Cha, H., <b>An, S.</b>, Choi, S., Yang, S., Park, S. H., Park, S.
                    "Study on Intention Recognition and Sensory Feedback Control of Robotic Prosthetic Hand Through EMG Classification and Proprioceptive Feedback Using Rule-based Haptic Device."
                    "IEEE Transactions on Haptics (ToH)."

      - layout: top-middle
        sub_title: International Conference Papers
      - layout: left
        sub_title: 2024
        index: C7
        description: <b>An, S.</b>, Kang, M., Kim, S., Chikontwe, P., Shen, L., & Park, S. H. 
                    "Subject-Adaptive Transfer Learning Using Resting State EEG Signals for Cross-Subject EEG Motor Imagery Classification" 
                    International Conference on Medical Image Computing and Computer-Assisted Intervention (MICCAI) (Early Accept<Top11%).
      - layout: left
        sub_title: 2024
        index: C6
        description: <b>An, S.</b>, Shen. L., & Park, S. H. 
          "Motor Imagery EEG Signal Generation from Resting-State Signal" 
          Annual International Conference of the IEEE Engineering in Medicine & Biology Society Research Poster (EMBC Research Poster).
      - layout: left
        sub_title: 2024
        index: C5
        paper_link:
          url: https://arxiv.org/abs/2312.13783
          icon: fas fa-paperclip
          title: Paper Link
        description: Kim, S., <b>An, S.</b>, Chikontwe, P., Kang, M., Adeli, E., Phol, K. M., & Park, S. H. 
          "Few Shot Part Segmentation Reveals Compositional Logic for Industrial Anomaly Detection" 
          AAAI Conference on Artificial Intelligence (AAAI).
      - layout: left
        sub_title: 2021
        index: C4
        paper_link:
          url: https://ojs.aaai.org/index.php/AAAI/article/view/16275
          icon: fas fa-paperclip
          title: Paper Link
        description: Kim, S., <b>An, S.</b>, Chikontwe, P., & Park, S. H.
          "Bidirectional RNN-based few shot learning for 3d medical image segmentation"
          AAAI Conference on Artificial Intelligence (AAAI).
      - layout: left
        sub_title: 2021
        index: C3
        paper_link:
          url: https://link.springer.com/chapter/10.1007/978-3-030-87602-9_1
          icon: fas fa-paperclip
          title: Paper Link
        description: Won. D, Jung. E., <b>An, S.</b>, Chikontwe, P., & Park, S. H.
          "Low-Dose CT Denoising Using Pseudo-CT Image Pairs"
          MICCAI PRIME (International Workshop on PRedictive Intelligence In MEdicine).
      - layout: left
        sub_title: 2020
        index: C2
        paper_link:
          url: https://link.springer.com/chapter/10.1007/978-3-030-59354-4_7
          icon: fas fa-paperclip
          title: Paper Link
        description: Won. D, <b>An, S.</b>, Park, S. H., & Ye, D. H.
          "Low-dose CT denoising using octave convolution with high and low frequency bands"
          MICCAI PRIME (International Workshop on PRedictive Intelligence In MEdicine).
      - layout: left
        sub_title: 2020
        index: C1
        paper_link:
          url: https://ieeexplore.ieee.org/abstract/document/9340933
          icon: fas fa-paperclip
          title: Paper Link
        code_link:
          url: https://github.com/SionAn/FewShotEEG
          icon: fab fa-github
          title: Code Link
        description: <b>An, S.</b>, Kim, S., Chikontwe, P., & Park, S. H.
          "Few-Shot Relation Learning with Attention for EEG-based Motor Imagery Classification"
          IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS).

      - layout: top-middle
        sub_title: Domestic Conference Papers
      - layout: left
        sub_title: 2023
        index: D5
        description: Lee. D, <b>An, S.</b>, & Park, S. H.
          "Anomaly Detection on Abdominal CT and Brain MRI based on Densitiy-Estimation"
          Workshop on Image Processing and Image Understanding (IPIU).
      - layout: left
        sub_title: 2022
        index: D4
        description: <b>An, S.</b>, Kim, S., Chikontwe, P., Park, H., Abdul, T., & Park, S. H.
          "Dual Attention Relation Network for Few Shot EEG Motor Imagery Classification"
          Summer Annual Conference of IEIE.
      - layout: left
        sub_title: 2021
        index: D3
        description: Kim, S., <b>An, S.</b>, Chikontwe, P., & Park, S. H.
          "Few Shot Learning based on Bidirectional Recurrent Neural Network for 3D Medical Image Segmentation"
          Workshop on Image Processing and Image Understanding (IPIU).
      - layout: left
        sub_title: 2020
        index: D2
        description: <b>An, S.</b>, Kim, S., & Park, S. H.
          "Neural Spike Detection using Deep Convolutional Neural Network"
          Workshop on Image Processing and Image Understanding (IPIU).
      - layout: left
        sub_title: 2017
        index: D1
        description: Lee, H., <b>An, S.</b>, Jeon, S., Kim, K., Lee, S., Lee, S., Kim, J. Y., & Choi, H.
          "Development of Helical Drilling Microrobot Based on Catheter and Guidewire for Chronic Total Occlusion Treatment"
          The Korean Society of Mechanical Engineers Annual Meeting.

  - title: Review Services
    layout: text
    content: |
      - IEEE Transactions on Industrial Informatics (TII)
      - IEEE Transactions on Neural Networks and Learning Systems (TNNLS)
      - IEEE Transactions on Neural Systems and Rehabilitation Engineering (TNSRE)
      - Cognitive Neurodynamics
      - International Conference on Medical Image Computing and Computer Assisted Intervention (MICCAI)

  - title: Awards
    layout: text
    content: |
      - (2023) DGIST Outstanding Researcher Award
      - (2023) DGIST Post-Graduate Research Abroad Awards
      - (2023) Industry-Academia Scholarship from the CTO team at LG Electronics
      - (2021) Ranked 3rd in SNUH Sleep AI Challenge
      - (2021) Paper Awards at ICROS 2021

## Footer
#footer_show_references: true
## references_title: References on request (Override references text)
#
## Build settings
#remote_theme: sproogen/resume-theme
#
#sass:
#  sass_dir: _sass
#  style: compressed
#
#plugins:
# - jekyll-seo-tag

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
